version: '3.2'

services:
  mongo:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
  notebook:
    image: drewbrns/houdini
    command: ./start_notebook.sh
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - NLTK_DATA=/app/bin/nltk_data/
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo
  api:
    image: drewbrns/houdini-api
    build: .
    command: python houdini/api/api.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - NLTK_DATA=/app/bin/nltk_data/      
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo