version: '3.2'

services:
  mongo:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
  notebook:
    image: ampsersandlabs/houdini
    command: ./start_notebook.sh
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo
  api:
    image: ampsersandlabs/houdini-api
    build: .
    command: python houdini/api.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo
  fetcher:
    image: ampsersandlabs/houdini-fetcher
    build: .
    command: python houdini/fetch_data.py
    volumes:
      - .:/app
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo